name: Build Images

env:
  location: westeurope

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    # paths:
    #       - '**/packer.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Evaluate Azure Context
        id: azure-context
        run: |
          echo "::set-output name=subscription::$(az account show --query "id" -o tsv)"

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ steps.azure-context.outputs.subscription }}
          template: ./arm/azuredeploy.json
          parameters: location=${{ env.location }}

      - id: packer-definitions
        name: Detect Packer Definitions
        run: | 
          echo "::set-output name=matrix::$(find . -type f -name 'packer.json' | jq -R -s -c 'split("\n")[:-1]')"

    outputs:
        matrix: ${{ steps.packer-definitions.outputs.matrix }}

  build:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
        matrix:
            imagePath: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1.0.0

      - name: Build Image
        run: |
          IMAGE="$(basename "$(dirname "${{ matrix.imagePath }}")")"
          echo $IMAGE
          packer build -var "image=$IMAGE" -var "location=${{ env.location }}" "${{ matrix.imagePath }}" 
